### ISSUE TITLE
"UserWarning: (rtime + duration) of block format" does not match

### ISSUE THREAD

**Issue by iluvcapra** [ebu/ebu_adm_renderer#11]
Hello-

I'm looking at an ADM created by a Dolby RMU and when I open it this way:

    admparser = openBw64Adm('ADM_TEST_WAV.wav')
    print(admparser.adm.audioObjects)

I get a bunch of messages in the console:

    /Users/u/src/adm_test/venv/lib/python3.7/site-packages/ear/fileio/adm/xml.py:1153: UserWarning: (rtime + duration) of block format AB_00031005_00000026 does not equal rtime of block format AB_00031005_00000027.id_b=bf_b.id))

I see these originate from a call to `_check_block_format_durations` in xml.py, can you explain why these warnings are being generated? Is an ADM from a Dolby RMU somehow not to spec, and is there a way to silence this warning already in the code that I'm not seeing?

**Comment by iluvcapra** [comment]
The RMU is a Dolby Atmos DAPS renderer v3.4.0.

**Comment by benjamin-weiss** [comment]
Try adding the optional `fix_block_format_durations` parameter.
```python
admparser = openBw64Adm('ADM_TEST_WAV.wav', fix_block_format_durations=True)
print(admparser.adm.audioObjects)
```
This should fix these issues in your ADM file automatically.

**Comment by iluvcapra** [comment]
What does this do exactly, does it change how the block formats sound?

**Comment by benjamin-weiss** [comment]
No. The warnings you are seeing are probably there because of floating point rounding issues. So if you enable the `fix_block_format_durations` option and the metadata in the ADM file is

    Start time of block 1 is 1 second and has a duration of 0.999999999999 second. 
    Start time of block 2 is 2 seconds.

the duration of block 1 will be fixed and set to 1 second.

**Comment by iluvcapra** [comment]
Okay that's great, I get it!

Just asking, if I were doing a PR, Is it worth implementing the time parameters as `fraction` instances?

**Comment by iluvcapra** [comment]
Oh wait they are fractions. Never mind O:)
