### ISSUE TITLE
API usage documentation

### ISSUE THREAD

**Issue by kickermeister** [ebu/ebu_adm_renderer#14]
I'm currently in the process of implementing a little tool using some of fileio components and had to realize that it is (at least for me) not completely straightforward how to write a BW64 file including an axml chunk / ADM parameters. I'm wondering whether it would be valuable or reasonable if some basic documentation would be added how the ADM / BW64 parts of the project should be used for ADM projects. I suppose that the BW64/ADM parts would be a separate project ideally.

**Comment by tomjnixon** [comment]
Yes, i agree completely. I think the best reference for reading/writing is currently the command-line utilities, but some real documentation would be good. I registered ear.readthedocs.io ages ago just in case.
