### ISSUE TITLE
EAR crashes rendring cartesian ADM....

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ebu_adm_renderer#41]
...with message

`'ObjectCartesianPosition' object has no attribute 'distance'`

which seems odd, as cartesian should not have a distance parameter.....

respective axml attached
[TAT prinzip Hoffnung ATMOS ADM neuer start.wav--amxl_DFMfix.xml.zip](https://github.com/ebu/ebu_adm_renderer/files/7253024/TAT.prinzip.Hoffnung.ATMOS.ADM.neuer.start.wav--amxl_DFMfix.xml.zip)

Any workaround possible?

**Comment by tomjnixon** [comment]
Hi, thanks for reporting this; unfortunately I couldn't get this error to occur. Please could you let me know:

- Which version of the EAR you're using (the version from github, or just running `pip install ear`?)
- What command-line arguments you are using.
- The full traceback: if you run `ear-render` with the `--debug` flag it will print more information when it crashes; please send the output starting with the line like `Traceback (most recent call last):`

**Comment by WernerBleisteiner** [comment]
Thanks Tom.
Just succeeded this time.

- Installed initially (2 years ago) with `pip install ear`.
   (should I better now switch to the GitHub version for more things being fixed?)
- arguments: see attached log in debug mode

Sorry, I may have got confused, as my aim is to create a binaural version from this file using https://github.com/IRT-Open-Source/binaural_nga_renderer
As this one's based on EAR, I didn't quite get if installing nga-binaural would effect (corrupt) a previously installed ear.
If I switch to git, I think I'd better go for pipenv...

As nga-binaural failed, I thought of cross check with EAR (and may had gotten things wrong).
Was astonished, as I could import this ADM in EAR Production Suite (however had to use a 0.7.0 beta first,
as it crashed on export).

[BASH-LOG-debug-ear-render-Dolby-ADM-TATORT-succes.rtf.zip](https://github.com/ebu/ebu_adm_renderer/files/7258068/BASH-LOG-debug-ear-render-Dolby-ADM-TATORT-succes.rtf.zip)
CLOSED

**Comment by tomjnixon** [comment]
Great, I've opened a couple of pull requests to make binaural_nga_renderer compatible with the latest EAR master, and to (hopefully) fix your bug.

I would recommend using the latest EAR; you could use two virtualenvs to keep them separate. There are some instructions for using virtualenvs, and installing the latest version, here: https://ear.readthedocs.io/en/latest/install.html#use-a-virtualenv

**Comment by WernerBleisteiner** [comment]
Thanks. 
Great that you've invested energy into readthedocs.
That'll help me a lot.
