### ISSUE TITLE
Files with many thousands of objects?

### ISSUE THREAD

**Issue by TomArrow** [ebu/ebu_adm_renderer#43]
I'm not sure where else to pose this question so I'll try here. After reading some of the documentation of the ADM metadata, it appears to me that the IDs of some item types like audioPackFormat have only 4 digits to save the unique ID of said item.

Is it then fair to assume that the specification has a hard limit of objects of those types at 9999? If not, what would be the correct way to go above that? My use case specifically would be to have a few hundred "physical" channels in the .WAV file and thousands or tens of thousands of objects at various points in time, often very short objects. I'd be happy to keep all the objects in a single audioContent, one per physical audio track. 

Aside from the ID issue, libbw64 seems to have a limit of 1024 track UIDs and this seems to get applied to the chna chunk. I do not actually need more than 1024 "physical" tracks but now I am wondering if I can reuse the same audioTrackUID, audioTrackFormatID, audioPackFormatID.

Those question arise after reading this document: https://adm.ebu.io/use_cases/dynamic_mixed.html

That document deals with multiple objects sharing the same "physical" track but each gets its own audioTrackUID which I imagine would easily bloat the chna chunk over 1024 items. Really for the most part, all the format info stays the same (it's the same bw64 file after all), except that I would like dynamic interpolated positioning data for each object. But that comes from the audioBlockFormat, which seems connected to the audioPackFormat via the audioChannelFormat, so do I need an individual audioPackFomat for each object? And if so, then the mentioned ID issue with only 4 free digits arises.

I suppose I could just limit myself to one object per track, but then I would have no proper logical distinction between unrelated objects and I would also have to let silence or lack of content be part of those objects. Which I suppose wouldn't affect the rendering in the grand scheme of things, but semantically it's not ideal.

For reference, my intended use case is to export ADM files from a video game engine, that's why it can be so many different objects at random times throughout the duration of the file.

As a side note, it would be great if it was possible to allow to let the ADM xml data to be saved in compressed form into the chunk. Gzip perhaps, or zlib or zstd. It should compress really well due to the repeated keywords and with a use case like mine, the filesize really adds up quickly. It's not terribly important though, would just be a nice-to-have.

**Comment by tomjnixon** [comment]
Hi, asking here is fine. I'm going to close this as it's not really an EAR issue, but feel free to ask follow-up questions.

> Is it then fair to assume that the specification has a hard limit of objects of those types at 9999?

The IDs are (or should be) hexadecimal, which gives a maximum of 65535 for 4 digits.

> Aside from the ID issue, libbw64 seems to have a limit of 1024 track UIDs and this seems to get applied to the chna chunk

This limit comes from having the chna chunk being written before the data chunk, which is generally preferred. You could just change '1024' to whatever number you need, but it's not the cleanest solution. There is a TODO in setChnaChunk to have it write the CHNA after data if it doesn't fit in the pre-allocated space, but that seems like it might cause other issues, as you'd end up with a file with multiple JUNK chunks.

Some other options would be:

- remove the CHNA chunk writing from Bw64Writer, and add your CHNA chunk to postDataChunks_ (with setAxmlChunk, which is badly named as it's not axml-specific)
- have setChnaChunk check against the size of the existing CHNA chunk -- that way you can call writeFile with a dummy CHNA chunk that's big enough for all your UIDs, and write the actual data later

In general you do need one CHNA entry per audioChannelFormat you want to render, so you can't work around this issue.

> so do I need an individual audioPackFomat for each object?

Not necessarily, you can have multiple audioChannelFormats in an audioPackFormat. This is really for cases like 'direct speakers' (channel-based content) where you really have one format with multiple channels; i'm not really sure that applies in your case.

The technical limitation is that when you reference your tracks from audioObjects, you have to reference all channels in the referenced audioPackFormat. In other words, if you group audioChannelFormats into an audioPackFormat, you can't then split them into separate audioObjects.

> I suppose I could just limit myself to one object per track, but then I would have no proper logical distinction between unrelated objects and I would also have to let silence or lack of content be part of those objects. Which I suppose wouldn't affect the rendering in the grand scheme of things, but semantically it's not ideal.

Yeah, I agree.

> For reference, my intended use case is to export ADM files from a video game engine, that's why it can be so many different objects at random times throughout the duration of the file.

This sounds fun!

> As a side note, it would be great if it was possible to allow to let the ADM xml data to be saved in compressed form into the chunk. Gzip perhaps, or zlib or zstd. It should compress really well due to the repeated keywords and with a use case like mine, the filesize really adds up quickly. It's not terribly important though, would just be a nice-to-have.

BS.2088-1 specifies a bxml chunk, which is the same as axml but (optionally) compressed with GZIP. I don't know if there's any support yet, though; none of the EBU tools do. I'd be interested to add it to the EAR, and maybe a chunk definition to libbw64 (though probably not automatic decompression, as that would introduce a dependency).
