### ISSUE TITLE
ruamel.yaml import error 

### ISSUE THREAD

**Issue by mxbolt** [ebu/ebu_adm_renderer#61]
ear command line tools fail to load due to import error:

> ImportError: cannot import name 'YAML' from 'ruamel.yaml' (/Users/<user>/.pyenv/versions/3.10.12/lib/python3.10/site-packages/ruamel.yaml.clib-0.2.7-py3.10-macosx-13.5-x86_64.egg/ruamel/yaml/__init__.py)

It seems the code is affected by ruamel.yaml versions after 0.17.21.

(_Platform: MacBook Pro 2019 (intel) macOS Ventura 13.5.1_)

**Comment by tomjnixon** [comment]
Hi, sorry about this. I'm not sure exactly what the problem is, but ruamel.yaml has caused too much trouble and we no longer need the features it provides, so are switching to PyYAML in #62 

Hopefully that fixes your problem?

**Comment by mxbolt** [comment]
Oh my bad, I didn't realise there was already a branch ready to go. Tested and it fixed the problem, all good.

**Comment by tomjnixon** [comment]
Great, thanks. The branch was new, it's not your fault!
