### ISSUE TITLE
How to use ear to edit aXML, chna and dbmd chunks in Dolby Atmos ADM BWF files?

### ISSUE THREAD

**Issue by npinto** [ebu/ebu_adm_renderer#69]
I'm curious how to use ear to read *and* write aXML, chna and dbmd chunks in Dolby Atmos ADM BWF files?

Especially the dbmd chunk:
https://github.com/DolbyLaboratories/dbmd-atmos-parser

Thanks!

**Comment by tomjnixon** [comment]
Hopefully answered in #67.
